baseURL = 'https://kindlemodding.org/'
languageCode = 'en-gb'
title = 'Kindle Modding Wiki'
disableKinds = ['taxonomy'] # We don't use this lol
uglyURLs = true
disablePathToLower = true

[outputs]
  home = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      [markup.goldmark.parser.attribute]
        block = true

[permalinks]
  page = ":contentbasename"